### ISSUE TITLE
New optimizations results in clients seeing inconsistent data values

### ISSUE THREAD

**Issue by jerrinsg** [vmware-samples/go-redis-pmem#6]
It is seen that with the recent optimizations where a transaction is kept alive until the pipeline is completely processed, clients can end up seeing inconsistent data values. 

The test file used to verify this can be accessed at https://github.com/vmware-samples/go-redis-pmem/blob/tests/tests/pipeline_test.go

The test creates two clients - client 1 and client 2. Client 1 builds a large pipeline of request and sends it to the server. Each request increments the value of data items `a` and `b` by one.

client 2 sends a request to the server to read the value of `a` and `b`. It then sets the value of `c` as `a+b`. Immediately after this point, an application crash is induced.

When the test is run again, the value of `a`, `b`, and `c` is retrieved. It is expected that the value of `c` will always be less than or equal to the current value of `a` and `b`. But on certain runs of the test, it is seen that this is not the case. E.g.:
```
➜  tests git:(tests) ✗ ~/go-pmem/bin/go test -run=Pipeline
First time initialization
Go-redis is ready to accept connections
Reading from client: EOF
Client 2 - Got a as  56  and b as  56 . Set c as  112
Reading from client: EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5ae8b4]

goroutine 242 [running]:
github.com/vmware-samples/go-redis-pmem/tests.client2()
	/home/jerrin/gocode/src/github.com/vmware-samples/go-redis-pmem/tests/pipeline_test.go:70 +0x2b4
created by github.com/vmware-samples/go-redis-pmem/tests.client1
	/home/jerrin/gocode/src/github.com/vmware-samples/go-redis-pmem/tests/pipeline_test.go:44 +0x30b
exit status 2
FAIL	github.com/vmware-samples/go-redis-pmem/tests	5.912s


➜  tests git:(tests) ✗ ~/go-pmem/bin/go test -run=Pipeline
Not a first time intialization
Go-redis is ready to accept connections
Got values as: a =  54  b =  54  c =  112
--- FAIL: TestPipeline (2.00s)
    pipeline_test.go:123: Invalid values
FAIL
exit status 1
FAIL	github.com/vmware-samples/go-redis-pmem/tests	2.008s
```

**Comment by pratapsu** [comment]
Jerrin:

Can you convert this into a pull request? I'd like to review the test code
in vscode after sync'ing my local client like  we spoke yesterday in the
project meeting.

Regards,

Pratap

**Comment by jerrinsg** [comment]
I have created a new pull request at https://github.com/vmware-samples/go-redis-pmem/pull/7

**Comment by jerrinsg** [comment]
Closing this issue - reverted the commits that introduced this issue (#5).
